name: Decrypt and Run main.py

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Decrypt main.zip
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python decrypt.py

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Specify the Python version you're using

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Execute main.py
        run: python main.py
